mail-server-postal/postal/config/routes.rb
Rails.application.routes.draw do

  scope "org/:org_permalink", :as => 'organization' do
    resources :domains, :only => [:index, :new, :create, :destroy] do
      match :verify, :on => :member, :via => [:get, :post]
      get :setup, :on => :member
      post :check, :on => :member
    end
    resources :servers, :except => [:index] do
      resources :domains, :only => [:index, :new, :create, :destroy] do
        match :verify, :on => :member, :via => [:get, :post]
        get :setup, :on => :member
        post :check, :on => :member
      end
      resources :track_domains do
        post :toggle_ssl, :on => :member
        post :check, :on => :member
      end
      resources :credentials
      resources :routes
      resources :http_endpoints
      resources :smtp_endpoints
      resources :address_endpoints
      resources :ip_pool_rules
      resources :messages do
        get :incoming, :on => :collection
        get :outgoing, :on => :collection
        get :held, :on => :collection
        get :activity, :on => :member
        get :plain, :on => :member
        get :html, :on => :member
        get :html_raw, :on => :member
        get :attachments, :on => :member
        get :headers, :on => :member
        get :attachment, :on => :member
        get :download, :on => :member
        get :spam_checks, :on => :member
        post :retry, :on => :member
        post :cancel_hold, :on => :member
        get :suppressions, :on => :collection
        delete :remove_from_queue, :on => :member
        get :deliveries, :on => :member
      end
      resources :webhooks do
        get :history, :on => :collection
        get 'history/:uuid', :on => :collection, :action => 'history_request', :as => 'history_request'
      end
      get :limits, :on => :member
      get :retention, :on => :member
      get :queue, :on => :member
      get :spam, :on => :member
      get :delete, :on => :member
      get 'help/outgoing' => 'help#outgoing'
      get 'help/incoming' => 'help#incoming'
      get :advanced, :on => :member
      post :suspend, :on => :member
      post :unsuspend, :on => :member
    end

    resources :ip_pool_rules
    resources :ip_pools, :controller => 'organization_ip_pools' do
      put :assignments, :on => :collection
    end
    root 'servers#index'
    get 'settings' => 'organizations#edit'
    patch 'settings' => 'organizations#update'
    get 'delete' => 'organizations#delete'
    delete 'delete' => 'organizations#destroy'
  end

  resources :organizations, :except => [:index]
  resources :users
  resources :ip_pools do
    resources :ip_addresses
  end

  get 'settings' => 'user#edit'
  patch 'settings' => 'user#update'
  post 'persist' => 'sessions#persist'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/token' => 'sessions#create_with_token'
  delete 'logout' => 'sessions#destroy'
  match 'login/reset' => 'sessions#begin_password_reset', :via => [:get, :post]
  match 'login/reset/:token' => 'sessions#finish_password_reset', :via => [:get, :post]


  get 'ip' => 'sessions#ip'

  root 'organizations#index'
end

mail-server-postal/postal/app/models/ip_pool.rb
# == Schema Information
#
# Table name: ip_pools
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  uuid       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  default    :boolean          default(FALSE)
#
# Indexes
#
#  index_ip_pools_on_uuid  (uuid)
#

class IPPool < ApplicationRecord

  include HasUUID

  validates :name, :presence => true

  has_many :ip_addresses, :dependent => :restrict_with_exception
  has_many :servers, :dependent => :restrict_with_exception
  has_many :organization_ip_pools, :dependent => :destroy
  has_many :organizations, :through => :organization_ip_pools
  has_many :ip_pool_rules, :dependent => :destroy

  def self.default
    where(:default => true).order(:id).first
  end

end

mail-server-postal/postal/app/controllers/ip_pools_controller.rb
class IPPoolsController < ApplicationController

  before_action :admin_required
  before_action { params[:id] && @ip_pool = IPPool.find_by_uuid!(params[:id]) }

  def index
    @ip_pools = IPPool.order(:name).to_a
  end

  def new
    @ip_pool = IPPool.new
  end

  def create
    @ip_pool = IPPool.new(safe_params)
    if @ip_pool.save
      redirect_to_with_json [:edit, @ip_pool], :notice => "IP Pool has been added successfully. You can now add IP addresses to it."
    else
      render_form_errors 'new', @ip_pool
    end
  end

  def update
    if @ip_pool.update(safe_params)
      redirect_to_with_json [:edit, @ip_pool], :notice => "IP Pool has been updated."
    else
      render_form_errors 'edit', @ip_pool
    end
  end

  def destroy
    @ip_pool.destroy
    redirect_to_with_json :ip_pools, :notice => "IP pool has been removed successfully."
  rescue ActiveRecord::DeleteRestrictionError => e
    redirect_to_with_json [:edit, @ip_pool], :alert => "IP pool cannot be removed because it is still assigned to servers/rules."
  end

  private

  def safe_params
    params.require(:ip_pool).permit(:name, :default)
  end

end

mail-server-postal/postal/app/views/ip_pools/_form.html.haml
= form_for @ip_pool, :remote => true do |f|
  = f.error_messages
  %fieldset.fieldSet.u-margin
    .fieldSet__field
      = f.label :name, :class => 'fieldSet__label'
      .fieldSet__input= f.text_field :name, :autofocus => true, :class => 'input input--text'

  - if @ip_pool.persisted?
    %table.dataTable.u-margin-half
      %thead
        %tr
          %td IPv4
          %td IPv6
          %td Hostname
          %td Priority
      %tbody
        - ips = @ip_pool.ip_addresses.order_by_priority
        - if ips.empty?
          %tr
            %td.dataTable__empty{:colspan => 3} There are no IP addresses assigned to this pool yet.
        - else
          - for ip in ips
            %tr
              %td{:width => "20%"}= link_to ip.ipv4, [:edit, @ip_pool, ip], :class => "u-link"
              %td{:width => "35%"}= ip.ipv6
              %td{:width => "35%"}= ip.hostname
              %td{:width => "10%"}= ip.priority
    %p= link_to "Add an IP address to pool", [:new, @ip_pool, :ip_address], :class => "u-link"


  .fieldSetSubmit.buttonSet
    = f.submit :class => 'button button--positive js-form-submit'
    .fieldSetSubmit__delete
      - if @ip_pool.persisted?
        = link_to "Delete IP pool", [@ip_pool], :class => 'button button--danger', :method => :delete, :remote => true, :data => {:confirm => "Are you sure you wish to remove this IP pool?"}

mail-server-postal/postal/app/views/ip_pools/edit.html.haml
- page_title << "IP Pools"
- page_title << @ip_pool.name

.pageHeader
  %h1.pageHeader__title
    %span.pageHeader__titlePrevious
      = link_to "IP Pools", :ip_pools
      &rarr;
      = @ip_pool.name
      &rarr;
    Edit

.pageContent.pageContent--compact
  = render 'form'

mail-server-postal/postal/app/views/ip_pools/index.html.haml
- page_title << "Welcome"

.pageHeader
  %h1.pageHeader__title IP Pools

.pageContent.pageContent--compact

  - if @ip_pools.empty?
    .noData.noData--clean
      %p.noData__title There are no IP pools configured.
      %p.noData__text
        All messages sent from your mail server can be sent from certain pools of
        IP addresses. Each server can be assigned to a pool and rules can be configured
        to route certain email through certain pools.
      %p.noData__button= link_to "Create the first IP pool", :new_ip_pool, :class => 'button button--positive'
  - else
    %p.pageContent__intro.u-margin
      IP pools are the addresses that your outgoing messages are sent from. You can
      create as many pools as you wish.

    %ul.largeList.u-margin
      - for ip_pool in @ip_pools
        %li.largeList__item
          = link_to edit_ip_pool_path(ip_pool), :class => 'largeList__link' do
            = ip_pool.name

    %p.u-center= link_to "Add another IP pool", :new_ip_pool, :class => 'button button--positive'

mail-server-postal/postal/app/views/ip_pools/new.html.haml
- page_title << "Create a new IP pool"
.pageHeader
  %h1.pageHeader__title
    %span.pageHeader__titlePrevious
      = link_to "IP Pools", :ip_pools
      &rarr;
    Create a new IP pool
.pageContent.pageContent--compact
  = render 'form'