mail-server-postal/postal/config/routes.rb
Rails.application.routes.draw do

  scope "org/:org_permalink", :as => 'organization' do
    resources :domains, :only => [:index, :new, :create, :destroy] do
      match :verify, :on => :member, :via => [:get, :post]
      get :setup, :on => :member
      post :check, :on => :member
    end
    resources :servers, :except => [:index] do
      resources :domains, :only => [:index, :new, :create, :destroy] do
        match :verify, :on => :member, :via => [:get, :post]
        get :setup, :on => :member
        post :check, :on => :member
      end
      resources :track_domains do
        post :toggle_ssl, :on => :member
        post :check, :on => :member
      end
      resources :credentials
      resources :routes
      resources :http_endpoints
      resources :smtp_endpoints
      resources :address_endpoints
      resources :ip_pool_rules
      resources :messages do
        get :incoming, :on => :collection
        get :outgoing, :on => :collection
        get :held, :on => :collection
        get :activity, :on => :member
        get :plain, :on => :member
        get :html, :on => :member
        get :html_raw, :on => :member
        get :attachments, :on => :member
        get :headers, :on => :member
        get :attachment, :on => :member
        get :download, :on => :member
        get :spam_checks, :on => :member
        post :retry, :on => :member
        post :cancel_hold, :on => :member
        get :suppressions, :on => :collection
        delete :remove_from_queue, :on => :member
        get :deliveries, :on => :member
      end
      resources :webhooks do
        get :history, :on => :collection
        get 'history/:uuid', :on => :collection, :action => 'history_request', :as => 'history_request'
      end
      get :limits, :on => :member
      get :retention, :on => :member
      get :queue, :on => :member
      get :spam, :on => :member
      get :delete, :on => :member
      get 'help/outgoing' => 'help#outgoing'
      get 'help/incoming' => 'help#incoming'
      get :advanced, :on => :member
      post :suspend, :on => :member
      post :unsuspend, :on => :member
    end

    resources :ip_pool_rules
    resources :ip_pools, :controller => 'organization_ip_pools' do
      put :assignments, :on => :collection
    end
    root 'servers#index'
    get 'settings' => 'organizations#edit'
    patch 'settings' => 'organizations#update'
    get 'delete' => 'organizations#delete'
    delete 'delete' => 'organizations#destroy'
  end

  resources :organizations, :except => [:index]
  resources :users
  resources :ip_pools do
    resources :ip_addresses
  end

  get 'settings' => 'user#edit'
  patch 'settings' => 'user#update'
  post 'persist' => 'sessions#persist'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/token' => 'sessions#create_with_token'
  delete 'logout' => 'sessions#destroy'
  match 'login/reset' => 'sessions#begin_password_reset', :via => [:get, :post]
  match 'login/reset/:token' => 'sessions#finish_password_reset', :via => [:get, :post]


  get 'ip' => 'sessions#ip'

  root 'organizations#index'
end

mail-server-postal/postal/app/models/webhook.rb
# == Schema Information
#
# Table name: webhooks
#
#  id           :integer          not null, primary key
#  server_id    :integer
#  uuid         :string(255)
#  name         :string(255)
#  url          :string(255)
#  last_used_at :datetime
#  all_events   :boolean          default(FALSE)
#  enabled      :boolean          default(TRUE)
#  sign         :boolean          default(TRUE)
#  created_at   :datetime
#  updated_at   :datetime
#
# Indexes
#
#  index_webhooks_on_server_id  (server_id)
#

class Webhook < ApplicationRecord

  include HasUUID

  belongs_to :server
  has_many :webhook_events, :dependent => :destroy
  has_many :webhook_requests

  validates :name, :presence => true
  validates :url, :presence => true, :format => {:with => /\Ahttps?\:\/\/[a-z0-9\-\.\_\?\=\&\/\+:%@]+\z/i, :allow_blank => true}

  scope :enabled, -> { where(:enabled => true) }

  after_save :save_events

  when_attribute :all_events, :changes_to => true do
    after_save do
      self.webhook_events.destroy_all
    end
  end

  def events
    @events ||= webhook_events.map(&:event)
  end

  def events=(value)
    @events = value.map(&:to_s).select(&:present?)
  end

  def save_events
    if @events
      @events.each do |event|
        webhook_events.where(:event => event).first_or_create!
      end
      webhook_events.where.not(:event => @events).destroy_all
    end
  end

end

mail-server-postal/postal/app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  include WithinOrganization
  before_action { @server = organization.servers.present.find_by_permalink!(params[:server_id]) }
  before_action { params[:id] && @webhook = @server.webhooks.find_by_uuid!(params[:id]) }

  def index
    @webhooks = @server.webhooks.order(:url).to_a
  end

  def new
    @webhook = @server.webhooks.build(:all_events => true)
  end

  def create
    @webhook = @server.webhooks.build(safe_params)
    if @webhook.save
      redirect_to_with_json [organization, @server, :webhooks]
    else
      render_form_errors 'new', @webhook
    end
  end

  def update
    if @webhook.update(safe_params)
      redirect_to_with_json [organization, @server, :webhooks]
    else
      render_form_errors 'edit', @webhook
    end
  end

  def destroy
    @webhook.destroy
    redirect_to_with_json [organization, @server, :webhooks]
  end

  def history
    @current_page = params[:page] ? params[:page].to_i : 1
    @requests = @server.message_db.webhooks.list(@current_page)
  end

  def history_request
    @req = @server.message_db.webhooks.find(params[:uuid])
  end

  private

  def safe_params
    params.require(:webhook).permit(:name, :url, :all_events, :enabled, :events => [])
  end

end

mail-server-postal/postal/app/views/webhooks/_form.html.haml
= form_for [organization, @server, @webhook], :remote => true do |f|
  = f.error_messages
  %fieldset.fieldSet
    .fieldSet__field
      = f.label :name, :class => 'fieldSet__label'
      .fieldSet__input
        = f.text_field :name, :autofocus => true, :class => 'input input--text'
        %p.fieldSet__text
          Enter a name to describe this webhook. This is used so you can identify this webhook later in the web interface.

    .fieldSet__field
      = f.label :url, :class => 'fieldSet__label'
      .fieldSet__input
        = f.text_field :url, :class => 'input input--text'
        %p.fieldSet__text
          Enter the URL that you'd like us to send requests to. All requests will be POST requests with
          a JSON-encoded payload in the body of the request.
    .fieldSet__field
      = f.label :enabled, :class => 'fieldSet__label'
      .fieldSet__input
        = f.select :enabled, [["Yes - send requests to this webhook", true], ["No - do not send requests at the moment", false]], {},:class => 'input input--select'
        %p.fieldSet__text
          You can enable or disable this webhook without fully removing it from the system. If there are any outstanding
          webhook deliveries, they will still be completed even if disabled.

    .fieldSet__field
      = f.label :all_events, 'Events', :class => 'fieldSet__label'
      .fieldSet__input
        = hidden_field_tag 'webhook[events][]'
        = f.select :all_events, [["Yes - send all events to this URL", true], ["No - I'll choose which requests to send", false]], {},:class => 'input input--select fieldSet__checkboxListAfter js-checkbox-list-toggle'
        %ul.checkboxList{:class => [@webhook.all_events? ? 'is-hidden' : '']}
          - for event in WebhookEvent::EVENTS
            %li.checkboxList__item
              .checkboxList__checkbox= check_box_tag "webhook[events][]", event, @webhook.events.include?(event), :id => "event_#{event}"
              .checkboxList__label
                = label_tag "event_#{event}", event, :class => 'checkboxList__actualLabel checkboxList__devEvent'
                %p.checkBoxList__text= t("webhook_events.#{event.underscore}")

  .fieldSetSubmit.buttonSet
    = f.submit @webhook.new_record? ? "Create Webhook" : "Save Webhook", :class => 'button button--positive js-form-submit'
    .fieldSetSubmit__delete
      - if f.object.persisted?
        = link_to "Delete Webhook", [organization, @server, @webhook], :remote => true, :class => 'button button--danger', :method => :delete, :data => {:confirm => "Are you sure you wish to delete this webhook?"}

mail-server-postal/postal/app/views/webhooks/_header.html.haml
.navBar.navBar--secondary
  %ul
    %li.navBar__item= link_to "Manage Webhooks", [organization, @server, :webhooks], :class => ['navBar__link', active_nav == :webhooks ? 'is-active' : '']
    %li.navBar__item= link_to "View History", [:history, organization, @server, :webhooks], :class => ['navBar__link', active_nav == :history ? 'is-active' : '']

mail-server-postal/postal/app/views/webhooks/edit.html.haml
- page_title << @server.name
- page_title << "Webhooks"
- page_title << "Edit"

= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :webhooks
= render 'header', :active_nav => :webhooks
.pageContent.pageContent--compact
  = render 'form'

mail-server-postal/postal/app/views/webhooks/history.html.haml
- page_title << @server.name
- page_title << "Webhooks"
- page_title << "History"

= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :webhooks
= render 'header', :active_nav => :history

.pageContent.pageContent--compact
  - if @requests[:records].empty?
    .noData.noData--clean
      %h2.noData__title No webhook requests recorded.
      %p.noData__text
        This page shows the last 10 days worth of webhook requests that have been sent by Postal. This page will
        populate automatically as webhooks are dispatched.

  - else
    %p.pageContent__intro.u-margin
      This page shows a list of all webhook requests which have been sent for this server. These are kept for 10 days before being
      removed. Click on a request for additional information.
    %ul.webhookRequestList
      - for req in @requests[:records]
        %li.webhookRequestList__item
          = link_to history_request_organization_server_webhooks_path(organization, @server, req.uuid), :class => 'webhookRequestList__link' do
            .webhookRequestList__top
              %p.webhookRequestList__status
                %span.label{:class => "label--http-status-#{req.status_code.to_s[0,1]}"}= req.status_code
              %p.webhookRequestList__time= req.timestamp.strftime("%d/%m/%Y at %H:%M:%S")
              %p.webhookRequestList__event= req.event
            %p.webhookRequestList__url= req.url || "Unknown"

    = render 'shared/message_db_pagination', :data => @requests, :name => 'request'

mail-server-postal/postal/app/views/webhooks/history_request.html.haml
- page_title << @server.name
- page_title << "Webhooks"
- page_title << "History"

= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :webhooks
= render 'header', :active_nav => :history

.pageContent.pageContent--compact
  %dl.pageContent__definitions.u-margin
    %dt URL
    %dd= @req.url
    %dt Event
    %dd= @req.event
    %dt UUID
    %dd= @req.uuid

    %dt Timestamp
    %dd= @req.timestamp.strftime("%d/%m/%Y at %H:%M:%S")
    %dt HTTP Status Code
    %dd
      %span.label.label--large{:class => "label--http-status-#{@req.status_code.to_s[0,1]}"}= @req.status_code

    %dt Attempt
    %dd
      = @req.attempt
      - if @req.will_retry?
        (will be retried)

  %p.pageContent__title Payload
  %pre.codeBlock.u-margin.codeBlock--whitespace~ preserve @req.pretty_payload
  %p.pageContent__title Response Body
  %pre.codeBlock.u-margin= @req.body
  %p.u-margin= link_to "Back to history", [:history, organization, @server, :webhooks], :class => "button button--neutral"

mail-server-postal/postal/app/views/webhooks/index.html.haml
- page_title << @server.name
- page_title << "Webhooks"

= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :webhooks
= render 'header', :active_nav => :webhooks
.pageContent.pageContent--compact
  - if @webhooks.empty?
    .noData.noData--clean
      %h2.noData__title No webhooks have been configured for this server.
      %p.noData__text
        You haven't added any webhooks for this server yet. A webhook enables your web
        application to be notified when certain events occur in the lifecycle of the mail server.
      %p.noData__button= link_to "Add your first webhook", [:new, organization, @server, :webhook], :class => "button button--positive"
  - else
    %ul.webhookList.u-margin
      - for webhook in @webhooks
        %li.webhookList__item
          .webhookList__top
            %p.webhookList__name= link_to webhook.name, [:edit, organization, @server, webhook]
            %p.webhookList__labels
              - if webhook.enabled?
                %span.label.label--green Enabled
              - else
                %span.label.label--red Disabled
          .webhookList__bottom
            %p.webhookList__usageTime
              - if webhook.last_used_at
                Last sent request #{distance_of_time_in_words_to_now webhook.last_used_at}.
              - else
                Not used yet.
            %ul.webhookList__links
              %li.webhookList__link= link_to "Edit Webhook", [:edit, organization, @server, webhook]

    %p.u-center= link_to "Add another webhook", [:new, organization, @server, :webhook], :class => 'button button--positive'

mail-server-postal/postal/app/views/webhooks/new.html.haml
- page_title << @server.name
- page_title << "Webhooks"
- page_title << "New"

= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :webhooks
= render 'header', :active_nav => :webhooks
.pageContent.pageContent--compact
  = render 'form'